plugins {
    id 'application'
}

group = 'dev.eaglercraft.bridge'
version = '0.1.0-SNAPSHOT'

java { toolchain { languageVersion = JavaLanguageVersion.of(25) } }

application { mainClass = 'dev.eaglercraft.bridge.BridgeApplication' }


tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}
